name: Bug report
description: Use this template to report bugs
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Note:** If this is a support-related question (e.g. _How can I do XYZ?_), please post on the [Google Developers Community Discord](https://discord.gg/google-dev-community) server's #palm-api channel instead. This is a great place to interact with developers, and to learn, share, and support each other.
  - type: textarea
    id: desc
    attributes:
      label: Description of the bug:
  - type: textarea
    id: desc
    attributes:
      label: Actual vs expected behaviour:
  - type: textarea
    id: desc
    attributes:
      label: Any other information you'd like to share?      
